# Generated by Django 5.2.15 on 2026-06-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_uso_cpu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ram_utilizada_gb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('coletado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetrias', to='maquinas.maquina')),
            ],
            options={
                'db_table': 'telemetrias',
                'indexes': [models.Index(fields=['maquina', 'coletado_em'], name='telemetrias_maquina_bcb62a_idx')],
            },
        ),
    ]
