# Generated by Django 5.2.15 on 2026-06-12 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('machine_id_linux', models.CharField(max_length=255, unique=True)),
                ('modelo_cpu', models.CharField(blank=True, max_length=255)),
                ('total_ram_gb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome_sistema_operacional', models.CharField(max_length=128)),
                ('versao_sistema_operacional', models.CharField(max_length=128)),
                ('intervalo_coleta_segundos', models.PositiveIntegerField(default=10)),
                ('intervalo_envio_segundos', models.PositiveIntegerField(default=60)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_ping_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maquinas',
            },
        ),
    ]
