# Generated by Django 5.2.15 on 2026-06-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEnergetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp_cpu_watts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fator_idle_alpha', models.DecimalField(decimal_places=4, max_digits=5)),
                ('consumo_ram_por_gb', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_energeticas', to='maquinas.maquina')),
            ],
            options={
                'db_table': 'configuracoes_energeticas',
            },
        ),
    ]
